project/coderslab/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from exercises_app.views import SchoolView, SchoolClassView, my_view, StudentView, StudentGradeView, StudentSearchView,\
    CreateStudentView, PizzaToppingsView, ClassPresence, SetColor


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', SchoolView.as_view(), name="index"),
    path('class/<int:school_class>/', SchoolClassView.as_view(), name="school-class"),
    path('student/<int:student_id>/', StudentView.as_view(), name="student-view"),
    path('grade/<int:student_id>/<int:subject_id>/', StudentGradeView.as_view(), name="student-grade"),
    path('student_search/', StudentSearchView.as_view(), name="student-search"),
    path('add_student/', CreateStudentView.as_view(), name="student-add"),
    path('pizza/', PizzaToppingsView.as_view(), name="pizza"),
    path('class_presence/<int:student_id>/<str:date>/', ClassPresence.as_view(), name="classpresence"),
    path('set_color/', SetColor.as_view(), name="setcolor"),
    path('my_page/', my_view, name="my-view")
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/exercises_app/models.py
from django.db import models


SCHOOL_CLASS = (
    (1, "1a"),
    (2, "1b"),
    (3, "2a"),
    (4, "2b"),
    (5, "3a"),
    (6, "3b"),
)

GRADES = (
    (1, "1"),
    (1.5, "1+"),
    (1.75, "2-"),
    (2, "2"),
    (2.5, "2+"),
    (2.75, "3-"),
    (3, "3"),
    (3.5, "3+"),
    (3.75, "4-"),
    (4, "4"),
    (4.5, "4+"),
    (4.75, "5-"),
    (5, "5"),
    (5.5, "5+"),
    (5.75, "6-"),
    (6, "6")
)


class SchoolSubject(models.Model):
    name = models.CharField(max_length=64)
    teacher_name = models.CharField(max_length=64)


class Student(models.Model):
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    school_class = models.IntegerField(choices=SCHOOL_CLASS)
    grades = models.ManyToManyField(SchoolSubject, through="StudentGrades")
    year_of_birth = models.IntegerField(null=True)

    @property
    def name(self):
        return "{} {}".format(self.first_name, self.last_name)

    def __str__(self):
        return self.name


class StudentGrades(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    school_subject = models.ForeignKey(SchoolSubject, on_delete=models.CASCADE)
    grade = models.FloatField(choices=GRADES)


PIZZA_SIZES = (
    (0, "S"),
    (1, "M"),
    (2, "L"),
    (3, "XL")
)


class Toppings(models.Model):
    name = models.CharField(max_length=32)
    price = models.FloatField()

    def __str__(self):
        return f'{self.name} - {self.price}zł'


class Pizza(models.Model):
    size = models.IntegerField(choices=PIZZA_SIZES)
    toppings = models.ManyToManyField(Toppings)


class PresenceList(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    day = models.DateField()
    present = models.BooleanField(null=True)

project/exercises_app/forms.py
from django import forms
from .models import SCHOOL_CLASS, PIZZA_SIZES, Toppings


class StudentSearchForm(forms.Form):
    last_name = forms.CharField(label='Nazwisko ucznia', max_length=64)


class StudentForm(forms.Form):
    first_name = forms.CharField(label='Imię', max_length=64)
    last_name = forms.CharField(label='Nazwisko', max_length=64)
    school_class = forms.ChoiceField(label='Klasa', choices=SCHOOL_CLASS)
    year_of_birth = forms.IntegerField(label='Data urodzenia')


class PizzaToppingsForm(forms.Form):
    size = forms.ChoiceField(label='Rozmiar Twojej pizzy', choices=PIZZA_SIZES)
    toppings = forms.ModelMultipleChoiceField(
        label='Dodatki',
        queryset=Toppings.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )


class PresenceListForm(forms.Form):
    student = forms.IntegerField(label='Uczeń')
    day = forms.DateField(label='Dzień', widget=forms.HiddenInput)
    present = forms.BooleanField(label='Obecność', widget=forms.CheckboxInput, required=False)


COLORS = (
    ("BLACK", "BLACK"),
    ("WHITE", "WHITE"),
    ("RED", "RED"),
    ("YELLOW", "YELLOW"),
    ("BLUE", "BLUE")
)


class BackgroundColorForm(forms.Form):
    color = forms.ChoiceField(label='Wybierz kolor', choices=COLORS)

project/exercises_app/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View

from .forms import StudentSearchForm, StudentForm, PizzaToppingsForm, PresenceListForm, BackgroundColorForm
from .models import SCHOOL_CLASS, Student, SchoolSubject, StudentGrades, Pizza, PresenceList


class SchoolView(View):
    def get(self, request):
        html = """<!doctype html>
        <html>
            <head><meta charset="utf-8"></head>
            <body>
                <h1>Szkoła podstawowa nr 1 im. Chucka Norrisa.</h1>
                <h2>Klasy:</h2>
                <ul>
                    {}
                </ul>
            </body>
        </html>
        """
        class_list = []
        for school_class in SCHOOL_CLASS:
            class_list.append("<li><a href='/class/{}'>{}</a></li>".format(school_class[0], school_class[1]))
        classes_part = "".join(class_list)
        return HttpResponse(html.format(classes_part))


class SchoolClassView(View):
    def get(self, request, school_class):
        students = Student.objects.filter(school_class=school_class).order_by('last_name')
        return render(request, "class.html", {"students": students,
                                              "class_name": SCHOOL_CLASS[int(school_class) - 1][1]})


def my_view(request):
    context = {'main_page': 'Nagłówek H1'}
    return render(request, 'my_view.html', context)


class StudentView(View):
    def get(self, request, student_id):
        student = get_object_or_404(Student, id=student_id)
        subjects = SchoolSubject.objects.all()
        return render(request, "studentview.html", {"student": student,
                                                    "subjects": subjects})


class StudentGradeView(View):
    def get(self, request, student_id, subject_id):
        student = get_object_or_404(Student, id=student_id)
        subject = get_object_or_404(SchoolSubject, id=subject_id)
        grades = StudentGrades.objects.filter(student=student_id, school_subject=subject_id)

        average_grade = round(sum(grade.grade for grade in grades) / len(grades), 2)

        return render(request, "gradesview.html", {"student": student,
                                                   "subject": subject,
                                                   "grades": grades,
                                                   "average": average_grade})


class StudentSearchView(View):
    def get(self, request):
        search_form = StudentSearchForm()
        context = {'search_form': search_form}
        return render(request, 'student_search.html', context)

    def post(self, request):
        search_form = StudentSearchForm(request.POST)
        if search_form.is_valid():
            last_name = search_form.cleaned_data['last_name']
            students = Student.objects.filter(last_name__icontains=last_name)
            context = {"students": students, 'search_form': search_form, 'students': 'empty'}
            return render(request, 'student_search.html', context)
        else:
            context = {'search_form': search_form, 'students': 'empty'}
            return render(request, 'student_search.html', context)


class CreateStudentView(View):
    def get(self, request):
        create_form = StudentForm()
        context = {'create_form': create_form}
        return render(request, 'student_create.html', context)

    def post(self, request):
        create_form = StudentForm(request.POST)
        if create_form.is_valid():
            first_name = create_form.cleaned_data['first_name']
            last_name = create_form.cleaned_data['last_name']
            school_class = create_form.cleaned_data['school_class']
            year_of_birth = create_form.cleaned_data['year_of_birth']
            student = Student.objects.create(
                last_name=last_name, first_name=first_name, school_class=school_class, year_of_birth=year_of_birth)
            return redirect('student-view', student_id=student.id)


class PizzaToppingsView(View):
    def get(self, request):
        form = PizzaToppingsForm()
        context = {'form': form}
        return render(request, 'pizza_toppings.html', context)

    def post(self, request):
        form = PizzaToppingsForm(request.POST)
        if form.is_valid():
            size = form.cleaned_data['size']
            toppings = form.cleaned_data['toppings']
            pizza = Pizza.objects.create(size=size)
            pizza.toppings.set(toppings)
            context = {'form': PizzaToppingsForm()}
            return render(request, 'pizza_toppings.html', context)


class ClassPresence(View):
    def get(self, request, student_id, date):
        student = Student.objects.get(id=student_id)
        logbook = PresenceListForm(initial={'student': student.id, 'day': date})
        context = {'logbook': logbook}
        return render(request, 'classpresence.html', context)

    def post(self, request):
        logbook = PresenceList(request.POST)
        if logbook.is_valid():
            student = logbook.cleaned_data['student']
            day = logbook.cleaned_data['day']
            present = logbook.cleaned_data['present']
            presencelist = PresenceList.objects.create(student=student, day=day, present=present)
            context = {'form': PresenceList()}
            return render(request, 'classpresence.html', context)


class SetColor(View):
    def get(self, request):
        colorform = BackgroundColorForm()
        context = {'colorform': colorform}
        return render(request, 'backgroundcolor.html', context)

    def post(self, request):
        colorform = BackgroundColorForm(request.POST)
        if colorform.is_valid():
            color = colorform.cleaned_data['color']
            context = {'form': BackgroundColorForm, 'color': color}
            return render(request, 'backgroundcolor.html', context)

project/exercises_app/templates/backgroundcolor.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST" action="">
    <body style="background-color: {{ color }}"></body>
    {% csrf_token %}
    {{ colorform }}
    <input type="submit" value="Dodaj">
    </form>
{% endblock %}

project/exercises_app/templates/base.html
{% load static %}

<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %}Szkoła CodersLab{% endblock %}</title>
    </head>
    <body>
        <div>
            <img src="{% static 'logo.png' %}" alt="School logo">
        </div>
        {% block content %}{% endblock %}
    </body>
</html>

project/exercises_app/templates/class.html
{% extends 'base.html' %}

{% block content %}
    <h1>Klasa {{ class_name }}</h1>
    <h2>Uczniowie</h2>
    <ol>
        {%for student in students %}
        <li>{{ student.last_name }}  {{ student.first_name }}</li>
        {% endfor %}
    </ol>
{% endblock %}

project/exercises_app/templates/classpresence.html
{% extends 'base.html' %}

{% block content %}
  <h2>Lista obecności</h2>
  <form method="post" action="">
    {% csrf_token %}
    {{ logbook }}
    <input type="submit" value="Zapisz">
  </form>
{% endblock %}

project/exercises_app/templates/gradesview.html
{% extends 'base.html' %}

{% block content %}
    <h2>Uczeń:</h2>
    <p><b>Imię i Nazwisko: </b>{{ student.first_name }} {{ student.last_name }}</p>
    <p><b>Klasa: </b>{{ student.get_school_class_display }}</p>
    <h2>Przedmiot:</h2>
    <p><b>Przedmiot: </b>{{ subject.name }}</p>
    <p><b>Nauczyciel: </b>{{ subject.teacher_name }}</p>
    <h2>Oceny:</h2>
    <ul>
        {%for grade in grades %}
        <li>{{ grade.get_grade_display }}</li>
        {% endfor %}
    </ul>
<p><b>Średnia: </b>{{ average }}</p>
{% endblock %}

project/exercises_app/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Szkoła podstawowa nr 1 im. Chucka Norrisa.</h1>
    <h2>Klasy:</h2>
    <ul>
        {}
    </ul>
{% endblock %}

project/exercises_app/templates/my_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{ main_page }}</h1>
<p>Authors: {{ authors }}</p>
</body>
</html>

project/exercises_app/templates/pizza_toppings.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Order Pizza</title>
</head>
<body>
<form method="post" action="">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Wypiecz">
    </form>
</body>
</html>

project/exercises_app/templates/student_create.html
{% extends 'base.html' %}

{% block content %}
  <h2>Dodaj ucznia</h2>
  <form method="post" action="">
    {% csrf_token %}
    {{ create_form }}
    <input type="submit" value="Dodaj ucznia">
  </form>
{% endblock %}

project/exercises_app/templates/student_search.html
{% extends 'base.html' %}

{% block content %}
  <h2>Znajdź ucznia</h2>
  <form method="post" action="">
    {% csrf_token %}
    {{ search_form }}
    <input type="submit" value="Szukaj">
  </form>
  {% if students != 'empty' %}
  <ol>
    {% for student in students %}
      <li>{{student.last_name}} {{student.first_name}}</li>
    {% empty %}
     <li>Brak wyników.</li>
    {% endfor %}
  </ol>
  {% endif %}
{% endblock %}

project/exercises_app/templates/studentview.html
{% extends 'base.html' %}

{% block content %}
    <h2>Uczeń:</h2>
    <p><b>Imię: </b>{{ student.first_name }}</p>
    <p><b>Nazwisko: </b>{{ student.last_name }}</p>
    <p><b>Klasa: </b>{{ student.get_school_class_display }}</p>
    <p><b>Data urodzenia: </b>{{ student.year_of_birth }}</p>
    <h2>Przedmioty:</h2>
    <ul>
    {% for subject in subjects %}
        <li>
            <a href={% url 'student-grade' student_id=student.id subject_id=subject.id %}>{{ subject.name }}</a>
        </li>
    {% endfor %}
    </ul>
{% endblock %}